using System.Xml.Linq;
using ApimPolicyCompiler.Cli;
using ApimPolicyCompiler.Core;

namespace ApimPolicyCompiler.Tests;

public sealed class CompilerSnapshotTests
{
    private static readonly string FixtureRoot = Path.Combine(AppContext.BaseDirectory, "Fixtures");

    [Theory]
    [MemberData(nameof(ValidFixtures))]
    public void Valid_fixtures_match_xml_snapshots(string fixture)
    {
        var json = File.ReadAllText(fixture);
        var result = RateLimitCompiler.CompileJson(json);

        Assert.True(result.Success, string.Join(Environment.NewLine, result.Diagnostics));
        Assert.NotNull(result.Xml);
        Assert.NotNull(result.Sha256);
        Assert.Equal(File.ReadAllText(Path.ChangeExtension(fixture, ".fragment.xml.snap")), result.Xml);
        XDocument.Parse(result.Xml);
        Assert.Equal(result.Sha256, RateLimitCompiler.ComputeSha256(result.Xml));
    }

    [Theory]
    [MemberData(nameof(ValidFixtures))]
    public void Valid_fixtures_satisfy_generated_policy_contract(string fixture)
    {
        var document = XDocument.Parse(CompileFixture(fixture));

        var errors = GeneratedPolicyContract.Validate(document);

        Assert.Empty(errors);
    }

    [Theory]
    [MemberData(nameof(ValidFixtures))]
    public void Valid_fixture_policy_expressions_compile(string fixture)
    {
        var document = XDocument.Parse(CompileFixture(fixture));
        var expressions = PolicyExpressionExtractor.Extract(document);
        var compiler = new PolicyExpressionCompiler();

        var staticErrors = PolicyExpressionCompiler.ValidateStaticPolicySubset(expressions);
        Assert.Empty(staticErrors);
        foreach (var expression in expressions)
        {
            compiler.Compile(expression);
        }
    }

    [Theory]
    [MemberData(nameof(InvalidFixtures))]
    public void Invalid_fixtures_match_diagnostic_snapshots(string fixture)
    {
        var json = File.ReadAllText(fixture);
        var result = RateLimitCompiler.CompileJson(json);

        Assert.False(result.Success);
        Assert.Null(result.Xml);
        Assert.Equal(File.ReadAllText(Path.ChangeExtension(fixture, ".diagnostics.snap")), FormatDiagnostics(result.Diagnostics));
    }

    [Fact]
    public void Output_is_deterministic_across_repeated_runs()
    {
        var json = File.ReadAllText(Path.Combine(FixtureRoot, "valid", "multiple-rules.json"));

        var first = RateLimitCompiler.CompileJson(json);
        var second = RateLimitCompiler.CompileJson(json);

        Assert.True(first.Success);
        Assert.Equal(first.Xml, second.Xml);
        Assert.Equal(first.Sha256, second.Sha256);
    }

    [Fact]
    public void Client_counter_keys_read_oauth_client_id_variable()
    {
        var json = File.ReadAllText(Path.Combine(FixtureRoot, "valid", "key-modes.json"));

        var result = RateLimitCompiler.CompileJson(json);

        Assert.True(result.Success);
        var document = XDocument.Parse(result.Xml!);
        var counterKeys = document.Descendants("rate-limit-by-key")
            .Select(static x => x.Attribute("counter-key")?.Value)
            .ToArray();
        Assert.NotEmpty(counterKeys);
        Assert.All(counterKeys, static x => Assert.Contains("context.Variables[\"oauthClientId\"]", x));
    }

    [Fact]
    public void Rate_limit_headers_are_omitted_by_default_and_emitted_when_requested()
    {
        var json = File.ReadAllText(Path.Combine(FixtureRoot, "valid", "default-prefix-rule.json"));

        var defaultResult = RateLimitCompiler.CompileJson(json);
        var optInResult = RateLimitCompiler.CompileJson(json, CompilerOptions.Default with { EmitRateLimitHeaders = true });

        Assert.True(defaultResult.Success);
        Assert.DoesNotContain("X-RateLimit-Remaining-", defaultResult.Xml);
        Assert.DoesNotContain("X-RateLimit-Limit-", defaultResult.Xml);
        Assert.Contains("retry-after-header-name=\"Retry-After\"", defaultResult.Xml);

        Assert.True(optInResult.Success);
        Assert.Contains("X-RateLimit-Remaining-dialogporten-default", optInResult.Xml);
        Assert.Contains("X-RateLimit-Limit-dialogporten-default", optInResult.Xml);

        var contractErrors = GeneratedPolicyContract.Validate(XDocument.Parse(optInResult.Xml!), emitRateLimitHeaders: true);
        Assert.Empty(contractErrors);
    }

    [Fact]
    public void Generated_xml_is_marked_as_compiler_generated()
    {
        var json = File.ReadAllText(Path.Combine(FixtureRoot, "valid", "default-prefix-rule.json"));

        var result = RateLimitCompiler.CompileJson(json);

        Assert.True(result.Success);
        Assert.Contains("Generated by apim-policy-compiler. Do not edit manually.", result.Xml);
    }

    [Fact]
    public void Client_id_preamble_uses_specialized_payload_extractor()
    {
        var json = File.ReadAllText(Path.Combine(FixtureRoot, "valid", "default-prefix-rule.json"));

        var result = RateLimitCompiler.CompileJson(json);

        Assert.True(result.Success);
        Assert.Contains("var json = Convert.FromBase64String(payload)", result.Xml);
        Assert.Contains("json[i + 10] != (byte)'&quot;'", result.Xml);
        Assert.Contains("System.Text.Encoding.ASCII.GetString(json, start, end - start)", result.Xml);
        Assert.DoesNotContain("var token =", result.Xml);
        Assert.DoesNotContain("token.IndexOf", result.Xml);
        Assert.DoesNotContain(".AsJwt()", result.Xml);
    }

    [Fact]
    public void Client_id_variable_name_can_be_overridden()
    {
        var json = File.ReadAllText(Path.Combine(FixtureRoot, "valid", "caller-match.json"));

        var result = RateLimitCompiler.CompileJson(json, CompilerOptions.Default with { ClientIdVariableName = "customClientId" });

        Assert.True(result.Success);
        Assert.Contains("context.Variables[&quot;customClientId&quot;]", result.Xml);
        Assert.Contains("name=\"customClientId\"", result.Xml);
        Assert.DoesNotContain("context.Variables[&quot;oauthClientId&quot;]", result.Xml);
        Assert.DoesNotContain("name=\"oauthClientId\"", result.Xml);
        Assert.Contains("(string)context.Variables[&quot;customClientId&quot;] == &quot;partner-a&quot;", result.Xml);
    }

    [Fact]
    public void Disabled_config_emits_empty_fragment_and_applies_no_rate_limits()
    {
        var xml = CompileFixture(Path.Combine(FixtureRoot, "valid", "disabled-config.json"));

        var document = XDocument.Parse(xml);
        Assert.Empty(document.Root!.Elements("set-variable"));
        Assert.Empty(document.Root!.Elements("rate-limit-by-key"));

        var run = new PolicyHarness().Run(xml, CreateAuthorizedContext("client-a", "/"));
        Assert.Empty(run.AppliedRateLimits);
    }

    [Fact]
    public void Authorization_header_resolves_client_id_with_specialized_preamble()
    {
        var xml = CompileFixture(Path.Combine(FixtureRoot, "valid", "preamble-bearer-jwt.json"));
        var harness = new PolicyHarness();

        var missingAuthorization = harness.Run(xml, new FakeContext());
        Assert.Equal("", missingAuthorization.Variables["oauthClientId"]);
        Assert.Empty(missingAuthorization.AppliedRateLimits);

        var nonBearer = new FakeContext();
        nonBearer.Request.Headers["Authorization"] = "Basic value";
        var nonBearerResult = harness.Run(xml, nonBearer);
        Assert.Equal("", nonBearerResult.Variables["oauthClientId"]);
        Assert.Empty(nonBearerResult.AppliedRateLimits);

        var invalidJwt = new FakeContext();
        invalidJwt.Request.Headers["Authorization"] = "Bearer not-a-jwt";
        var invalidJwtResult = harness.Run(xml, invalidJwt);
        Assert.Equal("", invalidJwtResult.Variables["oauthClientId"]);
        Assert.Empty(invalidJwtResult.AppliedRateLimits);

        var validJwt = CreateAuthorizedContext("client-a", "/jwt/orders");
        var validJwtResult = harness.Run(xml, validJwt);
        Assert.Equal("client-a", validJwtResult.Variables["oauthClientId"]);
        Assert.Single(validJwtResult.AppliedRateLimits);
        Assert.Equal("dialogporten:jwt:client-id:client-a", validJwtResult.AppliedRateLimits.Single().CounterKey);
    }

    [Fact]
    public void Existing_non_empty_client_id_variable_is_preserved()
    {
        var xml = CompileFixture(Path.Combine(FixtureRoot, "valid", "preamble-bearer-jwt.json"));
        var context = CreateAuthorizedContext("token-client", "/jwt/orders");
        context.Variables["oauthClientId"] = "existing-client";

        var result = new PolicyHarness().Run(xml, context);

        Assert.Equal("existing-client", result.Variables["oauthClientId"]);
        Assert.Equal("dialogporten:jwt:client-id:existing-client", result.AppliedRateLimits.Single().CounterKey);
    }

    [Fact]
    public void Scope_and_client_id_caller_match_is_executed_behaviorally()
    {
        var xml = CompileFixture(Path.Combine(FixtureRoot, "valid", "caller-match.json"));
        var harness = new PolicyHarness();

        var matching = CreateAuthorizedContext("partner-a", "/dialogporten/api/v1/orders/123", "orders:read orders:write");
        matching.Request.Method = "POST";
        var matchingResult = harness.Run(xml, matching);

        Assert.Equal("partner-a", matchingResult.Variables["oauthClientId"]);
        Assert.Equal(" orders:read orders:write ", matchingResult.Variables["oauthScopes"]);
        Assert.Single(matchingResult.AppliedRateLimits);

        var substringOnly = CreateAuthorizedContext("partner-a", "/dialogporten/api/v1/orders/123", "orders:writer");
        substringOnly.Request.Method = "POST";
        var substringResult = harness.Run(xml, substringOnly);
        Assert.Empty(substringResult.AppliedRateLimits);

        var excluded = CreateAuthorizedContext("foobar", "/dialogporten/api/v1/orders/123", "orders:write");
        excluded.Request.Method = "POST";
        var excludedResult = harness.Run(xml, excluded);
        Assert.Empty(excludedResult.AppliedRateLimits);
    }

    [Fact]
    public void Match_modes_and_methods_are_executed_behaviorally()
    {
        var harness = new PolicyHarness();

        var anyPath = CompileFixture(Path.Combine(FixtureRoot, "valid", "any-path-rule.json"));
        var anyPathContext = CreateAuthorizedContext("client-a", "/anything");
        anyPathContext.Request.Method = "POST";
        Assert.Single(harness.Run(anyPath, anyPathContext).AppliedRateLimits);

        var wrongMethod = CreateAuthorizedContext("client-a", "/anything");
        wrongMethod.Request.Method = "GET";
        Assert.Empty(harness.Run(anyPath, wrongMethod).AppliedRateLimits);

        var exactPath = CompileFixture(Path.Combine(FixtureRoot, "valid", "exact-path-rule.json"));
        var exactMatch = CreateAuthorizedContext("client-a", "/dialogporten/api/v1/serviceowner/instances");
        exactMatch.Request.Method = "GET";
        Assert.Single(harness.Run(exactPath, exactMatch).AppliedRateLimits);

        var exactMiss = CreateAuthorizedContext("client-a", "/dialogporten/api/v1/serviceowner/instances/123");
        exactMiss.Request.Method = "GET";
        Assert.Empty(harness.Run(exactPath, exactMiss).AppliedRateLimits);

        var prefixAndWildcardMethod = CompileFixture(Path.Combine(FixtureRoot, "valid", "multiple-rules.json"));
        var prefixMatch = CreateAuthorizedContext("client-a", "/dialogporten/anything");
        prefixMatch.Request.Method = "DELETE";
        Assert.Equal(2, harness.Run(prefixAndWildcardMethod, prefixMatch).AppliedRateLimits.Count);
    }

    [Fact]
    public void Counter_keys_include_client_id_and_ip_as_configured()
    {
        var xml = CompileFixture(Path.Combine(FixtureRoot, "valid", "key-modes.json"));
        var context = CreateAuthorizedContext("client-a", "/client-ip/resource");
        context.Request.IpAddress = "203.0.113.10";

        var result = new PolicyHarness().Run(xml, context);

        Assert.Equal(
            ["dialogporten:client:client-id:client-a", "dialogporten:client-ip:client-id-ip:client-a:203.0.113.10"],
            result.AppliedRateLimits.Select(static x => x.CounterKey).ToArray());
    }

    [Fact]
    public void Exclude_rules_are_evaluated_before_limit_rules()
    {
        var json = File.ReadAllText(Path.Combine(FixtureRoot, "valid", "exclude-exact-path.json"));

        var result = RateLimitCompiler.CompileJson(json);

        Assert.True(result.Success);
        var document = XDocument.Parse(result.Xml!);
        var outerChoose = document.Root!.Elements("choose").Single(static x => x.Element("otherwise") is not null);
        Assert.Contains("/dialogporten/health", outerChoose.Element("when")!.Attribute("condition")!.Value);
        Assert.Empty(outerChoose.Element("when")!.Elements("rate-limit-by-key"));
        Assert.NotNull(outerChoose.Element("otherwise")!.Descendants("rate-limit-by-key").Single());

        var harness = new PolicyHarness();
        var excluded = CreateAuthorizedContext("client-a", "/dialogporten/health");
        excluded.Request.Method = "GET";
        Assert.Empty(harness.Run(result.Xml!, excluded).AppliedRateLimits);

        var limited = CreateAuthorizedContext("client-a", "/dialogporten/orders");
        limited.Request.Method = "GET";
        Assert.Single(harness.Run(result.Xml!, limited).AppliedRateLimits);
    }

    [Fact]
    public void Caller_match_supports_client_ids_and_scopes()
    {
        var json = File.ReadAllText(Path.Combine(FixtureRoot, "valid", "caller-match.json"));

        var result = RateLimitCompiler.CompileJson(json);

        Assert.True(result.Success, string.Join(Environment.NewLine, result.Diagnostics));
        Assert.Contains("name=\"oauthScopes\"", result.Xml);
        Assert.Contains("(string)context.Variables[&quot;oauthClientId&quot;] == &quot;partner-a&quot;", result.Xml);
        Assert.Contains(".Contains(&quot; orders:write &quot;, StringComparison.Ordinal)", result.Xml);
    }

    [Fact]
    public void Scopes_preamble_uses_specialized_payload_extractor()
    {
        var json = File.ReadAllText(Path.Combine(FixtureRoot, "valid", "caller-match.json"));

        var result = RateLimitCompiler.CompileJson(json);

        Assert.True(result.Success, string.Join(Environment.NewLine, result.Diagnostics));
        Assert.Contains("name=\"oauthScopes\"", result.Xml);
        Assert.Contains("name=\"apimPolicyCompilerJwtClaims\"", result.Xml);
        Assert.Contains("json[i + 5] == (byte)'e'", result.Xml);
        Assert.Contains("return clientId + &quot;\\n&quot; + scopes;", result.Xml);
        Assert.Contains("claims.Substring(separator + 1)", result.Xml);
        Assert.Equal(1, CountOccurrences(result.Xml!, "Convert.FromBase64String(payload)"));
        Assert.DoesNotContain(".AsJwt()", result.Xml);
    }

    [Fact]
    public void Cli_exit_codes_match_contract()
    {
        var valid = Path.Combine(FixtureRoot, "valid", "disabled-config.json");
        var invalid = Path.Combine(FixtureRoot, "invalid", "invalid-calls-renewal.json");

        Assert.Equal(2, Program.Run([], TextWriter.Null, TextWriter.Null));
        Assert.Equal(0, Program.Run(["rate-limit", "--input", valid, "--stdout"], TextWriter.Null, TextWriter.Null));
        Assert.Equal(1, Program.Run(["rate-limit", "--input", invalid, "--stdout"], TextWriter.Null, TextWriter.Null));
        Assert.Equal(2, Program.Run(["rate-limit", "--input", valid, "--stdout", "--client-id-variable-name", "bad/name"], TextWriter.Null, TextWriter.Null));
    }

    public static IEnumerable<object[]> ValidFixtures()
    {
        return Directory.EnumerateFiles(Path.Combine(FixtureRoot, "valid"), "*.json")
            .Order(StringComparer.Ordinal)
            .Select(static x => new object[] { x });
    }

    public static IEnumerable<object[]> InvalidFixtures()
    {
        return Directory.EnumerateFiles(Path.Combine(FixtureRoot, "invalid"), "*.json")
            .Order(StringComparer.Ordinal)
            .Select(static x => new object[] { x });
    }

    private static string FormatDiagnostics(IReadOnlyList<Diagnostic> diagnostics)
    {
        return string.Join(Environment.NewLine, diagnostics.Select(static x => x.ToString())) + Environment.NewLine;
    }

    private static string CompileFixture(string fixture, CompilerOptions? options = null)
    {
        var json = File.ReadAllText(fixture);
        var result = RateLimitCompiler.CompileJson(json, options ?? CompilerOptions.Default);

        Assert.True(result.Success, string.Join(Environment.NewLine, result.Diagnostics));
        Assert.NotNull(result.Xml);
        return result.Xml;
    }

    private static FakeContext CreateAuthorizedContext(string clientId, string path, string? scope = null)
    {
        var context = new FakeContext();
        context.Request.Method = "GET";
        context.Request.Url.Path = path;

        var claims = scope is null
            ? new[] { ("client_id", clientId) }
            : [("scope", scope), ("client_id", clientId)];
        context.Request.Headers["Authorization"] = JwtFixture.CreateAuthorizationHeader(claims);
        return context;
    }

    private static int CountOccurrences(string value, string search)
    {
        var count = 0;
        var index = 0;

        while ((index = value.IndexOf(search, index, StringComparison.Ordinal)) >= 0)
        {
            count++;
            index += search.Length;
        }

        return count;
    }
}
