using System.Globalization;
using System.Xml.Linq;

namespace ApimPolicyCompiler.Tests;

public static class GeneratedPolicyContract
{
    private static readonly HashSet<string> AllowedElements = new(StringComparer.Ordinal)
    {
        "fragment",
        "choose",
        "when",
        "otherwise",
        "set-variable",
        "rate-limit-by-key"
    };

    private static readonly HashSet<string> UnsupportedFragmentElements = new(StringComparer.Ordinal)
    {
        "inbound",
        "outbound",
        "backend",
        "on-error",
        "base",
        "include-fragment"
    };

    public static IReadOnlyList<string> Validate(XDocument document, bool emitRateLimitHeaders = false)
    {
        var errors = new List<string>();

        if (document.Root?.Name.LocalName != "fragment")
        {
            errors.Add("Root element must be <fragment>.");
            return errors;
        }

        if (!document.Root.Nodes().OfType<XComment>().Any(static x => x.Value.Contains("Generated by apim-policy-compiler", StringComparison.Ordinal)))
        {
            errors.Add("Generated fragment must contain the compiler-generated warning comment.");
        }

        foreach (var element in document.Root.DescendantsAndSelf())
        {
            var name = element.Name.LocalName;
            if (UnsupportedFragmentElements.Contains(name))
            {
                errors.Add($"Unsupported APIM fragment element <{name}> is emitted.");
            }

            if (!AllowedElements.Contains(name))
            {
                errors.Add($"Unexpected generated element <{name}>.");
            }
        }

        foreach (var choose in document.Descendants("choose"))
        {
            var children = choose.Elements().Select(static x => x.Name.LocalName).ToArray();
            if (!children.Contains("when", StringComparer.Ordinal))
            {
                errors.Add("<choose> must contain at least one <when> child.");
            }

            if (children.Count(static x => x == "otherwise") > 1)
            {
                errors.Add("<choose> can contain at most one <otherwise> child.");
            }

            if (children.Any(static x => x != "when" && x != "otherwise"))
            {
                errors.Add("<choose> can only contain <when> and <otherwise> children.");
            }
        }

        foreach (var when in document.Descendants("when"))
        {
            var condition = when.Attribute("condition")?.Value;
            if (string.IsNullOrWhiteSpace(condition))
            {
                errors.Add("<when> must have a condition attribute.");
            }
            else if (!IsExpression(condition))
            {
                errors.Add("<when> condition must be an @(...) expression.");
            }
        }

        foreach (var setVariable in document.Descendants("set-variable"))
        {
            if (string.IsNullOrWhiteSpace(setVariable.Attribute("name")?.Value))
            {
                errors.Add("<set-variable> must have a name attribute.");
            }

            var value = setVariable.Attribute("value")?.Value;
            if (string.IsNullOrWhiteSpace(value))
            {
                errors.Add("<set-variable> must have a value attribute.");
            }
            else if (!IsStatement(value))
            {
                errors.Add("<set-variable> value must be an @{...} statement.");
            }
        }

        foreach (var rateLimit in document.Descendants("rate-limit-by-key"))
        {
            RequirePositiveInteger(errors, rateLimit, "calls");
            RequirePositiveInteger(errors, rateLimit, "renewal-period");

            var counterKey = rateLimit.Attribute("counter-key")?.Value;
            if (string.IsNullOrWhiteSpace(counterKey) || !IsExpression(counterKey))
            {
                errors.Add("<rate-limit-by-key> counter-key must be an @(...) expression.");
            }

            if (rateLimit.Attribute("retry-after-header-name")?.Value != "Retry-After")
            {
                errors.Add("<rate-limit-by-key> must use Retry-After as retry-after-header-name.");
            }

            var hasRemaining = rateLimit.Attribute("remaining-calls-header-name") is not null;
            var hasTotal = rateLimit.Attribute("total-calls-header-name") is not null;
            if (emitRateLimitHeaders)
            {
                if (!hasRemaining || !hasTotal)
                {
                    errors.Add("Rate-limit headers must be emitted when requested.");
                }
            }
            else if (hasRemaining || hasTotal)
            {
                errors.Add("Rate-limit headers must not be emitted by default.");
            }
        }

        return errors;
    }

    private static void RequirePositiveInteger(List<string> errors, XElement element, string attributeName)
    {
        var value = element.Attribute(attributeName)?.Value;
        if (!int.TryParse(value, NumberStyles.None, CultureInfo.InvariantCulture, out var number) || number <= 0)
        {
            errors.Add($"<{element.Name.LocalName}> {attributeName} must be a positive integer.");
        }
    }

    private static bool IsExpression(string value)
    {
        return value.StartsWith("@(", StringComparison.Ordinal) && value.EndsWith(")", StringComparison.Ordinal);
    }

    private static bool IsStatement(string value)
    {
        return value.StartsWith("@{", StringComparison.Ordinal) && value.EndsWith("}", StringComparison.Ordinal);
    }
}
